name: IPTV Gelişmiş Katalog Güncelleme

on:
  push:
    paths:
      - 'liste.m3u'
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Depoyu Kopyala
      uses: actions/checkout@v3

    - name: Python Kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Scripti Calistir
      run: python stream.py

    - name: Degisiklikleri Kaydet ve Yukle
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Tüm yeni klasörleri ekle
        git add stream/tv/*.json
        git add meta/tv/*.json
        git add catalog/tv/*.json
        
        git diff --quiet && git diff --staged --quiet || (git commit -m "Katalog Güncellendi: $(date +'%Y-%m-%d %H:%M')" && git push)
